# Generated by Django 4.0.4 on 2022-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('users', models.TextField(default='')),
                ('phase', models.CharField(max_length=200)),
                ('points', models.TextField(default='')),
                ('inpu_words', models.TextField(default='')),
                ('word_bag', models.TextField(default='')),
                ('game_words', models.TextField(default='')),
                ('chains', models.TextField(default='')),
            ],
        ),
    ]
