# Generated by Django 4.0.4 on 2022-04-30 08:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('users', jsonfield.fields.JSONField()),
                ('inpu_words', jsonfield.fields.JSONField()),
                ('phase', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('points', jsonfield.fields.JSONField()),
                ('inpu_words', jsonfield.fields.JSONField()),
                ('word_bag', jsonfield.fields.JSONField()),
                ('game_words', jsonfield.fields.JSONField()),
                ('chains', jsonfield.fields.JSONField()),
            ],
        ),
    ]
